#pragma once

#include <Arduino.h>

#define BATTLEBANG_HIT_TARGET_STRINGIFY_INNER(value) #value
#define BATTLEBANG_HIT_TARGET_STRINGIFY(value) BATTLEBANG_HIT_TARGET_STRINGIFY_INNER(value)

// Build-time overrides are injected by scripts/hit_target_config.py from
// src/hit_target/config.json and shell environment variables. Device identity is
// derived at runtime from the ESP32 eFuse MAC address.

#ifdef BATTLEBANG_HIT_TARGET_BUILD_MAX_HITS
#undef BATTLEBANG_HIT_TARGET_MAX_HITS
#define BATTLEBANG_HIT_TARGET_MAX_HITS BATTLEBANG_HIT_TARGET_BUILD_MAX_HITS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_HP_PHASE_COUNT
#undef BATTLEBANG_HIT_TARGET_HP_PHASE_COUNT
#define BATTLEBANG_HIT_TARGET_HP_PHASE_COUNT BATTLEBANG_HIT_TARGET_BUILD_HP_PHASE_COUNT
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_HITS_PER_PHASE
#undef BATTLEBANG_HIT_TARGET_HITS_PER_PHASE
#define BATTLEBANG_HIT_TARGET_HITS_PER_PHASE BATTLEBANG_HIT_TARGET_BUILD_HITS_PER_PHASE
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_HIT_THRESHOLD
#undef BATTLEBANG_HIT_TARGET_HIT_THRESHOLD
#define BATTLEBANG_HIT_TARGET_HIT_THRESHOLD BATTLEBANG_HIT_TARGET_BUILD_HIT_THRESHOLD
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_HIT_REARM_THRESHOLD
#undef BATTLEBANG_HIT_TARGET_HIT_REARM_THRESHOLD
#define BATTLEBANG_HIT_TARGET_HIT_REARM_THRESHOLD BATTLEBANG_HIT_TARGET_BUILD_HIT_REARM_THRESHOLD
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_HIT_COOLDOWN_MS
#undef BATTLEBANG_HIT_TARGET_HIT_COOLDOWN_MS
#define BATTLEBANG_HIT_TARGET_HIT_COOLDOWN_MS BATTLEBANG_HIT_TARGET_BUILD_HIT_COOLDOWN_MS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_HIT_REARM_STABLE_MS
#undef BATTLEBANG_HIT_TARGET_HIT_REARM_STABLE_MS
#define BATTLEBANG_HIT_TARGET_HIT_REARM_STABLE_MS BATTLEBANG_HIT_TARGET_BUILD_HIT_REARM_STABLE_MS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_HIT_REARM_CHECK_MS
#undef BATTLEBANG_HIT_TARGET_HIT_REARM_CHECK_MS
#define BATTLEBANG_HIT_TARGET_HIT_REARM_CHECK_MS BATTLEBANG_HIT_TARGET_BUILD_HIT_REARM_CHECK_MS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_DIGITAL_HIT_MIN_EDGES
#undef BATTLEBANG_HIT_TARGET_DIGITAL_HIT_MIN_EDGES
#define BATTLEBANG_HIT_TARGET_DIGITAL_HIT_MIN_EDGES BATTLEBANG_HIT_TARGET_BUILD_DIGITAL_HIT_MIN_EDGES
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_DIGITAL_ISR_DEBOUNCE_US
#undef BATTLEBANG_HIT_TARGET_DIGITAL_ISR_DEBOUNCE_US
#define BATTLEBANG_HIT_TARGET_DIGITAL_ISR_DEBOUNCE_US BATTLEBANG_HIT_TARGET_BUILD_DIGITAL_ISR_DEBOUNCE_US
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_CAPTURE_WINDOW_MS
#undef BATTLEBANG_HIT_TARGET_CAPTURE_WINDOW_MS
#define BATTLEBANG_HIT_TARGET_CAPTURE_WINDOW_MS BATTLEBANG_HIT_TARGET_BUILD_CAPTURE_WINDOW_MS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_DAMAGE_CHIP_MS
#undef BATTLEBANG_HIT_TARGET_DAMAGE_CHIP_MS
#define BATTLEBANG_HIT_TARGET_DAMAGE_CHIP_MS BATTLEBANG_HIT_TARGET_BUILD_DAMAGE_CHIP_MS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_PHASE_BACKFILL_GAP_LEDS
#undef BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_GAP_LEDS
#define BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_GAP_LEDS BATTLEBANG_HIT_TARGET_BUILD_PHASE_BACKFILL_GAP_LEDS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_PHASE_BACKFILL_SCALE
#undef BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_SCALE
#define BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_SCALE BATTLEBANG_HIT_TARGET_BUILD_PHASE_BACKFILL_SCALE
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_DEFEAT_RAINBOW_MS
#undef BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_MS
#define BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_MS BATTLEBANG_HIT_TARGET_BUILD_DEFEAT_RAINBOW_MS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_DEFEAT_BLACKOUT_MS
#undef BATTLEBANG_HIT_TARGET_DEFEAT_BLACKOUT_MS
#define BATTLEBANG_HIT_TARGET_DEFEAT_BLACKOUT_MS BATTLEBANG_HIT_TARGET_BUILD_DEFEAT_BLACKOUT_MS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_DEFEAT_RAINBOW_SPINS
#undef BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_SPINS
#define BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_SPINS BATTLEBANG_HIT_TARGET_BUILD_DEFEAT_RAINBOW_SPINS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_LED_PIN
#undef BATTLEBANG_HIT_TARGET_LED_PIN
#define BATTLEBANG_HIT_TARGET_LED_PIN BATTLEBANG_HIT_TARGET_BUILD_LED_PIN
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_LED_TYPE
#undef BATTLEBANG_HIT_TARGET_LED_TYPE
#define BATTLEBANG_HIT_TARGET_LED_TYPE BATTLEBANG_HIT_TARGET_BUILD_LED_TYPE
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_COLOR_ORDER
#undef BATTLEBANG_HIT_TARGET_COLOR_ORDER
#define BATTLEBANG_HIT_TARGET_COLOR_ORDER BATTLEBANG_HIT_TARGET_BUILD_COLOR_ORDER
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_NUM_LEDS
#undef BATTLEBANG_HIT_TARGET_NUM_LEDS
#define BATTLEBANG_HIT_TARGET_NUM_LEDS BATTLEBANG_HIT_TARGET_BUILD_NUM_LEDS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_LED_BRIGHTNESS
#undef BATTLEBANG_HIT_TARGET_LED_BRIGHTNESS
#define BATTLEBANG_HIT_TARGET_LED_BRIGHTNESS BATTLEBANG_HIT_TARGET_BUILD_LED_BRIGHTNESS
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_LED_MAX_MA
#undef BATTLEBANG_HIT_TARGET_LED_MAX_MA
#define BATTLEBANG_HIT_TARGET_LED_MAX_MA BATTLEBANG_HIT_TARGET_BUILD_LED_MAX_MA
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_PIEZO_DO_PIN
#undef BATTLEBANG_HIT_TARGET_PIEZO_DO_PIN
#define BATTLEBANG_HIT_TARGET_PIEZO_DO_PIN BATTLEBANG_HIT_TARGET_BUILD_PIEZO_DO_PIN
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_PIEZO_AO_PIN
#undef BATTLEBANG_HIT_TARGET_PIEZO_AO_PIN
#define BATTLEBANG_HIT_TARGET_PIEZO_AO_PIN BATTLEBANG_HIT_TARGET_BUILD_PIEZO_AO_PIN
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_RESET_BUTTON_PIN
#undef BATTLEBANG_HIT_TARGET_RESET_BUTTON_PIN
#define BATTLEBANG_HIT_TARGET_RESET_BUTTON_PIN BATTLEBANG_HIT_TARGET_BUILD_RESET_BUTTON_PIN
#endif

#ifdef BATTLEBANG_HIT_TARGET_BUILD_RESET_BUTTON_HOLD_MS
#undef BATTLEBANG_HIT_TARGET_RESET_BUTTON_HOLD_MS
#define BATTLEBANG_HIT_TARGET_RESET_BUTTON_HOLD_MS BATTLEBANG_HIT_TARGET_BUILD_RESET_BUTTON_HOLD_MS
#endif

#ifndef BATTLEBANG_HIT_TARGET_MAX_HITS
#define BATTLEBANG_HIT_TARGET_MAX_HITS 15
#endif

#ifndef BATTLEBANG_HIT_TARGET_HP_PHASE_COUNT
#define BATTLEBANG_HIT_TARGET_HP_PHASE_COUNT 3
#endif

#ifndef BATTLEBANG_HIT_TARGET_HITS_PER_PHASE
#define BATTLEBANG_HIT_TARGET_HITS_PER_PHASE 5
#endif

#ifndef BATTLEBANG_HIT_TARGET_HIT_THRESHOLD
#define BATTLEBANG_HIT_TARGET_HIT_THRESHOLD 1400
#endif

#ifndef BATTLEBANG_HIT_TARGET_HIT_REARM_THRESHOLD
#define BATTLEBANG_HIT_TARGET_HIT_REARM_THRESHOLD 800
#endif

#ifndef BATTLEBANG_HIT_TARGET_HIT_COOLDOWN_MS
#define BATTLEBANG_HIT_TARGET_HIT_COOLDOWN_MS 200
#endif

#ifndef BATTLEBANG_HIT_TARGET_HIT_REARM_STABLE_MS
#define BATTLEBANG_HIT_TARGET_HIT_REARM_STABLE_MS 80
#endif

#ifndef BATTLEBANG_HIT_TARGET_HIT_REARM_CHECK_MS
#define BATTLEBANG_HIT_TARGET_HIT_REARM_CHECK_MS 15
#endif

#ifndef BATTLEBANG_HIT_TARGET_DIGITAL_HIT_MIN_EDGES
#define BATTLEBANG_HIT_TARGET_DIGITAL_HIT_MIN_EDGES 2
#endif

#ifndef BATTLEBANG_HIT_TARGET_DIGITAL_ISR_DEBOUNCE_US
#define BATTLEBANG_HIT_TARGET_DIGITAL_ISR_DEBOUNCE_US 5000
#endif

#ifndef BATTLEBANG_HIT_TARGET_CAPTURE_WINDOW_MS
#define BATTLEBANG_HIT_TARGET_CAPTURE_WINDOW_MS 80
#endif

#ifndef BATTLEBANG_HIT_TARGET_DAMAGE_CHIP_MS
#define BATTLEBANG_HIT_TARGET_DAMAGE_CHIP_MS 240
#endif

#ifndef BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_GAP_LEDS
#define BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_GAP_LEDS 1
#endif

#ifndef BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_SCALE
#define BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_SCALE 96
#endif

#ifndef BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_MS
#define BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_MS 1900
#endif

#ifndef BATTLEBANG_HIT_TARGET_DEFEAT_BLACKOUT_MS
#define BATTLEBANG_HIT_TARGET_DEFEAT_BLACKOUT_MS 90
#endif

#ifndef BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_SPINS
#define BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_SPINS 2
#endif

#ifndef BATTLEBANG_HIT_TARGET_LED_PIN
#define BATTLEBANG_HIT_TARGET_LED_PIN 18
#endif

#ifndef BATTLEBANG_HIT_TARGET_NUM_LEDS
#define BATTLEBANG_HIT_TARGET_NUM_LEDS 60
#endif

#ifndef BATTLEBANG_HIT_TARGET_LED_TYPE
#define BATTLEBANG_HIT_TARGET_LED_TYPE WS2812B
#endif

#ifndef BATTLEBANG_HIT_TARGET_COLOR_ORDER
#define BATTLEBANG_HIT_TARGET_COLOR_ORDER GRB
#endif

#ifndef BATTLEBANG_HIT_TARGET_LED_BRIGHTNESS
#define BATTLEBANG_HIT_TARGET_LED_BRIGHTNESS 80
#endif

#ifndef BATTLEBANG_HIT_TARGET_LED_MAX_MA
#define BATTLEBANG_HIT_TARGET_LED_MAX_MA 1500
#endif

#ifndef BATTLEBANG_HIT_TARGET_PIEZO_DO_PIN
#define BATTLEBANG_HIT_TARGET_PIEZO_DO_PIN 27
#endif

#ifndef BATTLEBANG_HIT_TARGET_PIEZO_AO_PIN
#define BATTLEBANG_HIT_TARGET_PIEZO_AO_PIN -1
#endif

#ifndef BATTLEBANG_HIT_TARGET_RESET_BUTTON_PIN
#define BATTLEBANG_HIT_TARGET_RESET_BUTTON_PIN 0
#endif

#ifndef BATTLEBANG_HIT_TARGET_RESET_BUTTON_HOLD_MS
#define BATTLEBANG_HIT_TARGET_RESET_BUTTON_HOLD_MS 1200
#endif

namespace hit_target {

static constexpr const char* TARGET_ID_PREFIX = "hit_target";
static constexpr const char* FIRMWARE_NAME = "battlebang-generic-hit-target";
static constexpr uint32_t SERIAL_BAUD = 115200;

static constexpr int CONFIGURED_MAX_HITS = BATTLEBANG_HIT_TARGET_MAX_HITS;
static constexpr int HP_PHASE_COUNT = BATTLEBANG_HIT_TARGET_HP_PHASE_COUNT;
static constexpr int HITS_PER_PHASE = BATTLEBANG_HIT_TARGET_HITS_PER_PHASE;
static constexpr int MAX_HITS = HP_PHASE_COUNT * HITS_PER_PHASE;
static constexpr uint16_t HIT_THRESHOLD = BATTLEBANG_HIT_TARGET_HIT_THRESHOLD;
static constexpr uint16_t HIT_REARM_THRESHOLD = BATTLEBANG_HIT_TARGET_HIT_REARM_THRESHOLD;
static constexpr uint32_t HIT_COOLDOWN_MS = BATTLEBANG_HIT_TARGET_HIT_COOLDOWN_MS;
static constexpr uint32_t HIT_REARM_STABLE_MS = BATTLEBANG_HIT_TARGET_HIT_REARM_STABLE_MS;
static constexpr uint32_t HIT_REARM_CHECK_MS = BATTLEBANG_HIT_TARGET_HIT_REARM_CHECK_MS;
static constexpr uint16_t DIGITAL_HIT_MIN_EDGES = BATTLEBANG_HIT_TARGET_DIGITAL_HIT_MIN_EDGES;
static constexpr uint32_t DIGITAL_ISR_DEBOUNCE_US = BATTLEBANG_HIT_TARGET_DIGITAL_ISR_DEBOUNCE_US;
static constexpr uint32_t CAPTURE_WINDOW_MS = BATTLEBANG_HIT_TARGET_CAPTURE_WINDOW_MS;
static constexpr uint32_t DAMAGE_CHIP_MS = BATTLEBANG_HIT_TARGET_DAMAGE_CHIP_MS;
static constexpr int PHASE_BACKFILL_GAP_LEDS = BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_GAP_LEDS;
static constexpr uint8_t PHASE_BACKFILL_SCALE = BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_SCALE;
static constexpr uint32_t DEFEAT_RAINBOW_MS = BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_MS;
static constexpr uint32_t DEFEAT_BLACKOUT_MS = BATTLEBANG_HIT_TARGET_DEFEAT_BLACKOUT_MS;
static constexpr uint8_t DEFEAT_RAINBOW_SPINS = BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_SPINS;
static constexpr uint32_t ISR_DEBOUNCE_US = DIGITAL_ISR_DEBOUNCE_US;

static constexpr int LED_PIN = BATTLEBANG_HIT_TARGET_LED_PIN;
static constexpr int NUM_LEDS = BATTLEBANG_HIT_TARGET_NUM_LEDS;
static constexpr const char* LED_TYPE_NAME = BATTLEBANG_HIT_TARGET_STRINGIFY(BATTLEBANG_HIT_TARGET_LED_TYPE);
static constexpr const char* COLOR_ORDER_NAME = BATTLEBANG_HIT_TARGET_STRINGIFY(BATTLEBANG_HIT_TARGET_COLOR_ORDER);
static constexpr uint8_t LED_BRIGHTNESS = BATTLEBANG_HIT_TARGET_LED_BRIGHTNESS;
static constexpr uint8_t LED_MAX_VOLTS = 5;
static constexpr uint16_t LED_MAX_MA = BATTLEBANG_HIT_TARGET_LED_MAX_MA;
static constexpr uint32_t LED_SHOW_PERIOD_MS = 16;

static constexpr int PIEZO_DO_PIN = BATTLEBANG_HIT_TARGET_PIEZO_DO_PIN;
static constexpr int PIEZO_AO_PIN = BATTLEBANG_HIT_TARGET_PIEZO_AO_PIN;
static constexpr bool HAS_PIEZO_DO = PIEZO_DO_PIN >= 0;
static constexpr bool HAS_PIEZO_AO = PIEZO_AO_PIN >= 0;
static constexpr int RESET_BUTTON_PIN = BATTLEBANG_HIT_TARGET_RESET_BUTTON_PIN;
static constexpr bool HAS_RESET_BUTTON = RESET_BUTTON_PIN >= 0;
static constexpr uint32_t RESET_BUTTON_HOLD_MS = BATTLEBANG_HIT_TARGET_RESET_BUTTON_HOLD_MS;

static_assert(CONFIGURED_MAX_HITS > 0, "BATTLEBANG_HIT_TARGET_MAX_HITS must be positive");
static_assert(HP_PHASE_COUNT > 0, "BATTLEBANG_HIT_TARGET_HP_PHASE_COUNT must be positive");
static_assert(HITS_PER_PHASE > 0, "BATTLEBANG_HIT_TARGET_HITS_PER_PHASE must be positive");
static_assert(MAX_HITS == CONFIGURED_MAX_HITS,
              "BATTLEBANG_HIT_TARGET_MAX_HITS must equal HP_PHASE_COUNT * HITS_PER_PHASE");
static_assert(NUM_LEDS > 0, "BATTLEBANG_HIT_TARGET_NUM_LEDS must be positive");
static_assert(NUM_LEDS <= 240, "Keep NUM_LEDS bounded for ESP32 RAM/power budget");
static_assert(HIT_THRESHOLD > HIT_REARM_THRESHOLD, "Hit threshold should be above re-arm threshold");
static_assert(HIT_COOLDOWN_MS > 0, "BATTLEBANG_HIT_TARGET_HIT_COOLDOWN_MS must be positive");
static_assert(HIT_REARM_STABLE_MS > 0, "BATTLEBANG_HIT_TARGET_HIT_REARM_STABLE_MS must be positive");
static_assert(DIGITAL_HIT_MIN_EDGES > 0, "BATTLEBANG_HIT_TARGET_DIGITAL_HIT_MIN_EDGES must be positive");
static_assert(DIGITAL_ISR_DEBOUNCE_US > 0, "BATTLEBANG_HIT_TARGET_DIGITAL_ISR_DEBOUNCE_US must be positive");
static_assert(DAMAGE_CHIP_MS > 0, "BATTLEBANG_HIT_TARGET_DAMAGE_CHIP_MS must be positive");
static_assert(PHASE_BACKFILL_GAP_LEDS >= 0,
              "BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_GAP_LEDS must not be negative");
static_assert(PHASE_BACKFILL_SCALE > 0, "BATTLEBANG_HIT_TARGET_PHASE_BACKFILL_SCALE must be positive");
static_assert(DEFEAT_RAINBOW_MS > 0, "BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_MS must be positive");
static_assert(DEFEAT_BLACKOUT_MS <= 500,
              "BATTLEBANG_HIT_TARGET_DEFEAT_BLACKOUT_MS should stay short");
static_assert(DEFEAT_RAINBOW_SPINS > 0,
              "BATTLEBANG_HIT_TARGET_DEFEAT_RAINBOW_SPINS must be positive");
static_assert(RESET_BUTTON_HOLD_MS > 0, "BATTLEBANG_HIT_TARGET_RESET_BUTTON_HOLD_MS must be positive");
static_assert(HAS_PIEZO_DO || HAS_PIEZO_AO, "At least one piezo input pin is required");

}  // namespace hit_target
